/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package de.htwg.infe.blog;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class BlogEntry extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"BlogEntry\",\"namespace\":\"de.htwg.infe.blog\",\"fields\":[{\"name\":\"url\",\"type\":\"string\"},{\"name\":\"author\",\"type\":{\"type\":\"record\",\"name\":\"User\",\"fields\":[{\"name\":\"id\",\"type\":\"string\"},{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"mail\",\"type\":\"string\"},{\"name\":\"bild\",\"type\":\"string\"}]}},{\"name\":\"text\",\"type\":\"string\",\"default\":\"text\"},{\"name\":\"datum\",\"type\":\"long\",\"default\":0},{\"name\":\"titel\",\"type\":\"string\",\"default\":\"title\"},{\"name\":\"tag\",\"type\":{\"type\":\"array\",\"items\":\"string\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence url;
  @Deprecated public de.htwg.infe.blog.User author;
  @Deprecated public java.lang.CharSequence text;
  @Deprecated public long datum;
  @Deprecated public java.lang.CharSequence titel;
  @Deprecated public java.util.List<java.lang.CharSequence> tag;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public BlogEntry() {}

  /**
   * All-args constructor.
   */
  public BlogEntry(java.lang.CharSequence url, de.htwg.infe.blog.User author, java.lang.CharSequence text, java.lang.Long datum, java.lang.CharSequence titel, java.util.List<java.lang.CharSequence> tag) {
    this.url = url;
    this.author = author;
    this.text = text;
    this.datum = datum;
    this.titel = titel;
    this.tag = tag;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return url;
    case 1: return author;
    case 2: return text;
    case 3: return datum;
    case 4: return titel;
    case 5: return tag;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: url = (java.lang.CharSequence)value$; break;
    case 1: author = (de.htwg.infe.blog.User)value$; break;
    case 2: text = (java.lang.CharSequence)value$; break;
    case 3: datum = (java.lang.Long)value$; break;
    case 4: titel = (java.lang.CharSequence)value$; break;
    case 5: tag = (java.util.List<java.lang.CharSequence>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'url' field.
   */
  public java.lang.CharSequence getUrl() {
    return url;
  }

  /**
   * Sets the value of the 'url' field.
   * @param value the value to set.
   */
  public void setUrl(java.lang.CharSequence value) {
    this.url = value;
  }

  /**
   * Gets the value of the 'author' field.
   */
  public de.htwg.infe.blog.User getAuthor() {
    return author;
  }

  /**
   * Sets the value of the 'author' field.
   * @param value the value to set.
   */
  public void setAuthor(de.htwg.infe.blog.User value) {
    this.author = value;
  }

  /**
   * Gets the value of the 'text' field.
   */
  public java.lang.CharSequence getText() {
    return text;
  }

  /**
   * Sets the value of the 'text' field.
   * @param value the value to set.
   */
  public void setText(java.lang.CharSequence value) {
    this.text = value;
  }

  /**
   * Gets the value of the 'datum' field.
   */
  public java.lang.Long getDatum() {
    return datum;
  }

  /**
   * Sets the value of the 'datum' field.
   * @param value the value to set.
   */
  public void setDatum(java.lang.Long value) {
    this.datum = value;
  }

  /**
   * Gets the value of the 'titel' field.
   */
  public java.lang.CharSequence getTitel() {
    return titel;
  }

  /**
   * Sets the value of the 'titel' field.
   * @param value the value to set.
   */
  public void setTitel(java.lang.CharSequence value) {
    this.titel = value;
  }

  /**
   * Gets the value of the 'tag' field.
   */
  public java.util.List<java.lang.CharSequence> getTag() {
    return tag;
  }

  /**
   * Sets the value of the 'tag' field.
   * @param value the value to set.
   */
  public void setTag(java.util.List<java.lang.CharSequence> value) {
    this.tag = value;
  }

  /** Creates a new BlogEntry RecordBuilder */
  public static de.htwg.infe.blog.BlogEntry.Builder newBuilder() {
    return new de.htwg.infe.blog.BlogEntry.Builder();
  }
  
  /** Creates a new BlogEntry RecordBuilder by copying an existing Builder */
  public static de.htwg.infe.blog.BlogEntry.Builder newBuilder(de.htwg.infe.blog.BlogEntry.Builder other) {
    return new de.htwg.infe.blog.BlogEntry.Builder(other);
  }
  
  /** Creates a new BlogEntry RecordBuilder by copying an existing BlogEntry instance */
  public static de.htwg.infe.blog.BlogEntry.Builder newBuilder(de.htwg.infe.blog.BlogEntry other) {
    return new de.htwg.infe.blog.BlogEntry.Builder(other);
  }
  
  /**
   * RecordBuilder for BlogEntry instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<BlogEntry>
    implements org.apache.avro.data.RecordBuilder<BlogEntry> {

    private java.lang.CharSequence url;
    private de.htwg.infe.blog.User author;
    private java.lang.CharSequence text;
    private long datum;
    private java.lang.CharSequence titel;
    private java.util.List<java.lang.CharSequence> tag;

    /** Creates a new Builder */
    private Builder() {
      super(de.htwg.infe.blog.BlogEntry.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(de.htwg.infe.blog.BlogEntry.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.url)) {
        this.url = data().deepCopy(fields()[0].schema(), other.url);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.author)) {
        this.author = data().deepCopy(fields()[1].schema(), other.author);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.text)) {
        this.text = data().deepCopy(fields()[2].schema(), other.text);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.datum)) {
        this.datum = data().deepCopy(fields()[3].schema(), other.datum);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.titel)) {
        this.titel = data().deepCopy(fields()[4].schema(), other.titel);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.tag)) {
        this.tag = data().deepCopy(fields()[5].schema(), other.tag);
        fieldSetFlags()[5] = true;
      }
    }
    
    /** Creates a Builder by copying an existing BlogEntry instance */
    private Builder(de.htwg.infe.blog.BlogEntry other) {
            super(de.htwg.infe.blog.BlogEntry.SCHEMA$);
      if (isValidValue(fields()[0], other.url)) {
        this.url = data().deepCopy(fields()[0].schema(), other.url);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.author)) {
        this.author = data().deepCopy(fields()[1].schema(), other.author);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.text)) {
        this.text = data().deepCopy(fields()[2].schema(), other.text);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.datum)) {
        this.datum = data().deepCopy(fields()[3].schema(), other.datum);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.titel)) {
        this.titel = data().deepCopy(fields()[4].schema(), other.titel);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.tag)) {
        this.tag = data().deepCopy(fields()[5].schema(), other.tag);
        fieldSetFlags()[5] = true;
      }
    }

    /** Gets the value of the 'url' field */
    public java.lang.CharSequence getUrl() {
      return url;
    }
    
    /** Sets the value of the 'url' field */
    public de.htwg.infe.blog.BlogEntry.Builder setUrl(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.url = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'url' field has been set */
    public boolean hasUrl() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'url' field */
    public de.htwg.infe.blog.BlogEntry.Builder clearUrl() {
      url = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'author' field */
    public de.htwg.infe.blog.User getAuthor() {
      return author;
    }
    
    /** Sets the value of the 'author' field */
    public de.htwg.infe.blog.BlogEntry.Builder setAuthor(de.htwg.infe.blog.User value) {
      validate(fields()[1], value);
      this.author = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'author' field has been set */
    public boolean hasAuthor() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'author' field */
    public de.htwg.infe.blog.BlogEntry.Builder clearAuthor() {
      author = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'text' field */
    public java.lang.CharSequence getText() {
      return text;
    }
    
    /** Sets the value of the 'text' field */
    public de.htwg.infe.blog.BlogEntry.Builder setText(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.text = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'text' field has been set */
    public boolean hasText() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'text' field */
    public de.htwg.infe.blog.BlogEntry.Builder clearText() {
      text = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'datum' field */
    public java.lang.Long getDatum() {
      return datum;
    }
    
    /** Sets the value of the 'datum' field */
    public de.htwg.infe.blog.BlogEntry.Builder setDatum(long value) {
      validate(fields()[3], value);
      this.datum = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'datum' field has been set */
    public boolean hasDatum() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'datum' field */
    public de.htwg.infe.blog.BlogEntry.Builder clearDatum() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'titel' field */
    public java.lang.CharSequence getTitel() {
      return titel;
    }
    
    /** Sets the value of the 'titel' field */
    public de.htwg.infe.blog.BlogEntry.Builder setTitel(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.titel = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'titel' field has been set */
    public boolean hasTitel() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'titel' field */
    public de.htwg.infe.blog.BlogEntry.Builder clearTitel() {
      titel = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'tag' field */
    public java.util.List<java.lang.CharSequence> getTag() {
      return tag;
    }
    
    /** Sets the value of the 'tag' field */
    public de.htwg.infe.blog.BlogEntry.Builder setTag(java.util.List<java.lang.CharSequence> value) {
      validate(fields()[5], value);
      this.tag = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'tag' field has been set */
    public boolean hasTag() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'tag' field */
    public de.htwg.infe.blog.BlogEntry.Builder clearTag() {
      tag = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    //@Override
    public BlogEntry build() {
      try {
        BlogEntry record = new BlogEntry();
        record.url = fieldSetFlags()[0] ? this.url : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.author = fieldSetFlags()[1] ? this.author : (de.htwg.infe.blog.User) defaultValue(fields()[1]);
        record.text = fieldSetFlags()[2] ? this.text : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.datum = fieldSetFlags()[3] ? this.datum : (java.lang.Long) defaultValue(fields()[3]);
        record.titel = fieldSetFlags()[4] ? this.titel : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.tag = fieldSetFlags()[5] ? this.tag : (java.util.List<java.lang.CharSequence>) defaultValue(fields()[5]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
